import { useState } from 'react';
import { Wrench, Play, FileCode, Search, Terminal, BarChart3, Minimize2 } from 'lucide-react';
import './PageCommon.css';

const tools = [
  { name: 'read_file', category: '文件', desc: '读取文件内容', calls: 342, icon: FileCode },
  { name: 'search_code', category: '搜索', desc: '在代码库中搜索', calls: 189, icon: Search },
  { name: 'run_shell', category: '执行', desc: '执行 shell 命令', calls: 87, icon: Terminal },
  { name: 'analyze_ast', category: '分析', desc: 'AST 语法树分析', calls: 156, icon: BarChart3 },
  { name: 'find_code_smells', category: '审查', desc: '代码异味检测', calls: 234, icon: Search },
  { name: 'suggest_refactor', category: '审查', desc: '重构建议生成', calls: 78, icon: Wrench },
];

export default function Tools() {
  const [testingTool, setTestingTool] = useState<string | null>(null);
  const [testResult, setTestResult] = useState<string>('');

  const runTest = () => {
    setTestResult('Running...');
    setTimeout(() => {
      setTestResult('{\n  "status": "success",\n  "output": "Mock output generated by simulated tool run."\n}');
    }, 800);
  };

  return (
    <div className="animate-in">
      <div className="page-header">
        <h1><Wrench size={28} style={{ verticalAlign: 'middle', marginRight: 8 }} /> 工具注册</h1>
        <p>管理 Agent 可调用的工具，查看调用日志和 JSON Schema</p>
      </div>

      <div className="card-grid">
        {tools.map((tool) => (
          <div key={tool.name} className="card card-glow tool-card">
            <div className="tool-card-header">
              <div className="tool-icon"><tool.icon size={20} /></div>
              <span className="badge badge-blue">{tool.category}</span>
            </div>
            <h4 style={{ fontFamily: 'var(--font-mono)', fontSize: 14, marginBottom: 6 }}>{tool.name}</h4>
            <p className="text-secondary" style={{ fontSize: 13, marginBottom: 12 }}>{tool.desc}</p>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
              <span style={{ fontSize: 12, color: 'var(--text-tertiary)' }}>调用 {tool.calls} 次</span>
              <button className="btn btn-sm btn-secondary" onClick={() => setTestingTool(tool.name === testingTool ? null : tool.name)}>
                {testingTool === tool.name ? <Minimize2 size={14} /> : <Play size={14} />} {testingTool === tool.name ? '收起' : '测试'}
              </button>
            </div>
            {testingTool === tool.name && (
              <div style={{ marginTop: 16, padding: 12, background: 'var(--bg-card)', borderRadius: 6, border: '1px solid var(--border-color)' }}>
                <div style={{ fontSize: 12, color: 'var(--text-tertiary)', marginBottom: 8 }}>参数 (JSON)</div>
                <textarea 
                  style={{ width: '100%', height: 60, fontFamily: 'var(--font-mono)', fontSize: 12, background: 'var(--bg-main)', color: 'var(--text-primary)', border: '1px solid var(--border-color)', padding: 8, borderRadius: 4, resize: 'vertical' }}
                  defaultValue='{\n  "path": "/"\n}'
                />
                <button className="btn btn-sm btn-primary" style={{ marginTop: 8 }} onClick={runTest}><Play size={12}/> 执行测试</button>
                {testResult && (
                  <pre style={{ marginTop: 8, padding: 8, background: 'var(--bg-main)', fontSize: 12, borderRadius: 4, color: 'var(--accent-green-light)', whiteSpace: 'pre-wrap' }}>
                    {testResult}
                  </pre>
                )}
              </div>
            )}
          </div>
        ))}
      </div>
    </div>
  );
}
